phone_PHOTOS = {
    "iPhone X📱": r"C:\Users\hp\Desktop\iPhones\iPhone X.png",
    "iPhone Xr📱": r"C:\Users\hp\Desktop\iPhones\iPhone Xr.jpg",
    "iPhone Xs📱": r"C:\Users\hp\Desktop\iPhones\ip xs.jpg",
    "iPhone Xs Max📱": r"C:\Users\hp\Desktop\iPhones\ip xs max.webp",
    "iPhone 11📱": r"C:\Users\hp\Desktop\iPhones\apple-iphone-11.jpeg",
    "iPhone 11 Pro📱": r"C:\Users\hp\Desktop\iPhones\iPhone 11.jpg",
    "iPhone 11 Pro Max📱": r"C:\Users\hp\Desktop\iPhones\ip 12 pro.webp",
    "iPhone 12📱": r"C:\Users\hp\Desktop\iPhones\ip 12.jpg",
    "iPhone 12 Pro📱": r"C:\Users\hp\Desktop\iPhones\ip 12 pro.webp",
    "iPhone 12 Pro Max📱": r"C:\Users\hp\Desktop\iPhones\ip 12 pro max.jpg",
    "iPhone 13📱": r"C:\Users\hp\Desktop\iPhones\iPhone_13.webp",
    "iPhone 13 Pro📱": r"C:\Users\hp\Desktop\iPhones\ip 13 pro.jpg",
    "iPhone 13 Pro Max📱": r"C:\Users\hp\Desktop\iPhones\ip 13 pro max.jpg",
    "iPhone 14📱": r"C:\Users\hp\Desktop\iPhones\iphone-14.webp",
    "iPhone 14 Pro📱": r"C:\Users\hp\Desktop\iPhones\iPhone 14 pro.jpg",
    "iPhone 14 Pro Max📱": r"C:\Users\hp\Desktop\iPhones\ip 14 pro max.jpg",
    "Samsung Galaxy S21📱": r"C:\Users\hp\Desktop\Samsungs\sam S21.jpg",
    "Samsung Galaxy S21 Ultra📱": r"C:\Users\hp\Desktop\Samsungs\sam S21 ultra.jpg",
    "Samsung Galaxy Note 20📱": r"C:\Users\hp\Desktop\Samsungs\sam note 20.jpeg",
    "Samsung Galaxy Note 20 Ultra📱": r"C:\Users\hp\Desktop\Samsungs\61QNWgHXuiL.jpg",
    "Samsung Galaxy A52📱": r"C:\Users\hp\Desktop\Samsungs\sam A52.webp",
    "Samsung Galaxy A72📱": r"C:\Users\hp\Desktop\Samsungs\sam A72.jpg",
    "Samsung Galaxy Z Flip📱": r"C:\Users\hp\Desktop\Samsungs\Z flip.webp",
    "Samsung Galaxy Z Fold 3📱": r"C:\Users\hp\Desktop\Samsungs\maxresdefault.jpg",
    "Samsung Galaxy S22📱": r"C:\Users\hp\Desktop\Samsungs\AGnIoqoSbZs3SEPc70uE2Noi8z24HbtTd4HaELsy.jpg",
    "Samsung Galaxy S22 Ultra📱": r"C:\Users\hp\Desktop\Samsungs\q2E8-EQp7rrz6k-PqtAjXzCLeV1ewADj_2.jpg",
    "Xiaomi Mi 11📱": r"C:\Users\hp\Desktop\XiaoMi\XIA MI 11.jpg",
    "Xiaomi Mi 11 Ultra📱": r"C:\Users\hp\Desktop\XiaoMi\XIAOMI MI 11 ULTRA.jpg",
    "Xiaomi Redmi Note 10📱": r"C:\Users\hp\Desktop\XiaoMi\redmi Not 10.jpg",
    "Xiaomi Redmi Note 10 Pro📱": r"C:\Users\hp\Desktop\XiaoMi\redmi not 10 pro.jpg",
    "Xiaomi Poco X3 Pro📱": r"C:\Users\hp\Desktop\XiaoMi\poco x3 pro.jpeg",
    "Xiaomi Poco F3📱": r"C:\Users\hp\Desktop\XiaoMi\poco f3.jpg",
    "Xiaomi Mi 10T📱": r"C:\Users\hp\Desktop\XiaoMi\mi 10 ti.jpg",
    "Xiaomi Mi 10T Pro📱": r"C:\Users\hp\Desktop\XiaoMi\mi 10t pro.jpg",
    "Xiaomi Redmi 9📱": r"C:\Users\hp\Desktop\XiaoMi\mi 9.jpg",
    "Xiaomi Redmi 9A📱": r"C:\Users\hp\Desktop\XiaoMi\mi 9A.jpeg"
}

